#ifndef XML_PARSING_FLOAT_STANDARD_H
#define XML_PARSING_FLOAT_STANDARD_H

#include <stdlib.h>
#include <cmath>

/** @author Natalie Chmura
 * 
 * @brief This contains a function that converts each floating point decimal to a nanometer
 * (1 out of 10000000) scale! This is deemed nessesary to offset reach's use of full float for
 * tranlating the quaternion into an Isometry3D and back- thus a nanometer was deemed
 * a sufficent enough scale to round to!
 **/

/**
 * @namespace FloatSt 
 */
namespace FloatSt {

    /**
     * @class RoundSt 
     * 
     * @brief This class contains the function that parses the floats generated by the reach study and
     * converts them to their nanometer form!
     */
    class RoundSt {
        public:

            /**
             * @brief This function rounds a _Float64 to 7 decimal places!
             * 
             * @param number: The number that willbe rounded
            */
           static _Float64 roundNano(_Float64 number);
    };

}

#endif // namespace XML_PARSING_FLOAT_STANDARD_H