#ifndef PCD_PROCESSING_WRITE_PCD
#define PCD_PROCESSING_WRITE_PCD

#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/pose_array.hpp"
#include <string>
#include <fstream>
#include <iostream>

/**
 * @author Natalie Chmura
 * 
 * @brief A C++ file that processes an input of type poseArray and turns it into a .pcd 
 * file that can be used in the reach study
*/

/**
 * @namespace ProcessPCD
*/
namespace ProcessPCD {

/**
 * @class PCDFileProcessor
 * 
 * @brief This class processes a POseArray generated by the current "path-planning"
 *  algorothm into a PCD format that is able to be processed and used in the integration
 *  of the ROS_Industrial Reach package!
*/
class PCDFileProcessor {

    public:
    
    /**
     * @brief This function reads in a name of a file and a PoseArray and parses that 
     *  PoseArray into a PCD format!
     * 
     * @param PoseArray waypoints: The poses which will be converted to a pcd file
     * 
     * @param fname: The name of the file to be written to!
     * 
     * @returns An int indicating that the operation of writing to the file was a sucess!
    */
   static int writeFile(geometry_msgs::msg::PoseArray waypoints, std::string fname);

   /**
    * @brief This function mainly serves in esting the creation of a POseArray by reading
    *   in poses from a PCD file! 
    * 
    * @param fname: The file to be read from.
    * 
    * @returns A PoseArray as read from the PCD file!
   */
  static geometry_msgs::msg::PoseArray readPoses(std::string fname);

};

} // namespace ProcessPCD

#endif // PCD_PROCESSING_WRITE_PCD