#ifndef PCD_PROCESSING_WRITE_YAML
#define PCD_PROCESSING_WRITE_YAML

#include <string>
#include <fstream>
#include <iostream>
#include <yaml-cpp/yaml.h>

/**
 * @author Natalie Chmura
 * 
 * @brief A C++ file that writes a YAML file with a designated input path for the 
 *  generated pcd file also made in the pcd_processing package!
*/

/**
 * @namespace ProcessYAML
*/
namespace ProcessYAML {

/**
 * @class YAMLFileWriter
 * 
 * @brief This class takes a processed PCD file generated by the pcd (Also maybe optionally
 *  as well as any collsion meshes in the form of a ply file and a param determining the 
 *  endeffector distance though that would be in a seperate extension) And adds them to a yaml 
 *  file, tagged appropriatly.
*/
class YAMLFileWriter {

    public:

    /**
     * @brief This takes the information from poseArray and parses it into a yaml file that will be
     * used as a parameter in the reach study!
     * 
     * @param pathname: The path of the pcd file to include!
     * 
     * @param fname: The name of the file to write to!
    */
   static void writeYAML(std::string pathname, std::string fname);

};

} // namepsace ProcessYAML

#endif // PCD_PROCESSING_WRITE_YAML