geometry_msgs/PoseArray waypoints # The PoseArray which will be then configured into a pcd file that will be used in reach!
---
arp_msgs/YAMLFile yaml # The filepath for the yaml file that contains the reach configuration data, including the genrated pcd file!
bool sucess #If the file was written to sucessfully then the result is true! If any excpetions are thrown a false reult is returned!