geometry_msgs/PoseArray waypoints # The points along the path that reach will be performed on
---
string yaml_filepath # The filepath for the yaml file that contains the reach configuration data, including the genrated pcd file